name: release

on:
  workflow_dispatch:

jobs:
  release:
    # This line is critical for copy paste issues
    if: github.repository == 'push-based/ngx-fast-svg'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git user to "push-based.io - bot"
        shell: bash
        run: git config user.email "opensource@push-based.io" && git config user.name "push-based.io - bot"
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm i
      - name: build
        run: npm run nx -- affected:build
      - name: test
        run: npm run nx -- affected:test
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run nx -- affected --base=last-release --target=version
      - name: Tag last-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release -f

